import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <button className="bg-gray-600 text-white">Submit</button>
      </main>

      <footer >
        
      </footer>
    </div>
  )
}

export default Home
